spring.application.name=backend

# ========================
# Database Configuration
# ========================
spring.datasource.url=jdbc:mysql://localhost:3306/ai_doubt_solver
spring.datasource.username=root
spring.datasource.password=root123

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


file.upload-dir=uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
# ========================
# Server
# ========================
server.port=8080

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions